#!/usr/bin/env python3

import sys

def main(argv):
    if len(argv) != 2:
        print("Usage: generate_semicolon_error statement")
        return
    
    semicolon_position = argv[1].find(";")

    if semicolon_position == -1:
        print("No semicolon found in the statement")
        return
    
    error_message = f"Error 1:{semicolon_position + 1}\r\n{argv[1]}\r\n{' ' * semicolon_position}^\r\nunexpected ;\r\n\r\n"
    print(error_message.encode("ascii"))

if __name__ == "__main__":
    main(sys.argv)